spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: dangjia@2018
    pool:
      max-active: -1
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
server:
  port: 9004
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.30.95:9999/eureka/   # 指定注册中心的地址
  instance:
    preferIpAddress: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
hystrix.threadpool.default.coreSize: 2000
ribbon:
  ConnectTimeout: 20000
  ReadTimeout: 60000
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true

