spring:
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.30.95:9999/eureka/
zuul:
  maxTotalConnections: 20000 #配置路由连接数默认200
  ignored-services: dangjia-service-**                        # 需要忽视的服务(配置后将不会被路由)
  routes:
      ws :
        path: /ws/**
        url: http://172.16.30.95:9091 #
      user:
        path: /member/**
        service-id: dangjia-service-member
      basic:
        path: /basic/**
        service-id: dangjia-service-basic
      cache:
        path: /cache/**
        service-id: dangjia-service-cache
      task:
        path: /task/**
        service-id: dangjia-service-task
      job:
        path: /job/**
        service-id: dangjia-service-job
      upload:
        path: /upload/**
        service-id: dangjia-service-upload
      store:
        path: /store/**
        service-id: dangjia-service-store
      classroom:
        path: /classroom/**
        service-id: dangjia-service-classroom
      inset:
        path: /inset/**
        service-id: dangjia-service-inset
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
hystrix.threadpool.default.coreSize: 2000
zuul.sensitive-headers: true
