spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.53:3306/dangjia_master_showed?useUnicode=true
    username: root
    password: fengjiangit2
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 10
    minIdle: 10
    maxIdle: 100
    maxActive: 2000
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
server:
  port: 8110
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.48:8889/eureka/   # 指定注册中心的地址
  instance:
    preferIpAddress: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
hystrix.threadpool.default.coreSize: 2000
ribbon:
  ConnectTimeout: 20000
  ReadTimeout: 60000
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
huawei:
  obs:
    endPoint: https://obs.cn-south-1.myhuaweicloud.com
    keyId: KU8IPBQCNKNDOPMVDRDM
    keySecret: d2T2CFKnjY9FqTkxqqD0wDOTV8h5lQFvf7OhxTIV
    bucketName: dangjia-tests
