spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://139.159.192.14:3306/dangjia_changsha_showed?useUnicode=true
    username: qiyuxiang
    password: Fengjiang123!
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 10
    minIdle: 10
    maxIdle: 100
    maxActive: 2000
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    changsha:
      url: jdbc:mysql://139.159.192.14:3306/dangjia_changsha_showed?useUnicode=true
      username: qiyuxiang
      password: Fengjiang123!
    shenzhen:
      url: jdbc:mysql://139.159.192.14:3306/dangjia_shenzhen_showed?useUnicode=true
      username: qiyuxiang
      password: Fengjiang123!
  elasticsearch:
    jest:
      uris: http://172.16.30.95:9200
      read-timeout: 5000
server:
  port: 8113
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.83:8889/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000
hystrix.threadpool.default.coreSize: 500
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
