server:
  port: 9999
eureka:
  server:
        responseCacheUpdateInvervalMs: 3000
        eviction-interval-timer-in-ms: 3000
        enable-self-preservation: false
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: dangjia-eureka
