server:
  port: 8009
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.30.95:8888/eureka/   # 指定注册中心的地址
  instance:
    preferIpAddress: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000
hystrix.threadpool.default.coreSize: 500
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
