spring:
  data:
    elasticsearch:
      cluster-name: dangjia-test-es
      cluster-nodes: 134.175.187.54:9300
server:
  port: 7012
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.30.95:7777/eureka/   # 指定注册中心的地址
  instance:
    preferIpAddress: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000
hystrix.threadpool.default.coreSize: 500
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
