spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.16.30.95:3306/sesame_classroom_pre?useUnicode=true&characterEncoding=utf-8
    username: dangjia
    password: dangjia@int
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 10
    minIdle: 10
    maxIdle: 100
    maxActive: 2000
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  elasticsearch:
    jest:
      uris: http://172.16.30.95:9200
      read-timeout: 5000
server:
  port: 9013
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.16.7:9999/eureka/   # 指定注册中心的地址
  instance:
    preferIpAddress: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000
hystrix.threadpool.default.coreSize: 500
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
